Bert: !!python/object:Backend.algorithms.bert_topic.bert.Bert
  data: ''
  eventResutls: ''
  results_path: ../results/bert_topic/
SedTwik: !!python/object:Backend.algorithms.sedtwik.SedTwik.SedTwik
  data: ''
  eventResutls: ''
  results_path: ../results/sedwik/
Twembeddings: !!python/object:Backend.algorithms.twembed.Twembeddings.Twembeddings
  data: ''
  eventResutls: ''
  results_path: ../results/twembeddings/
